version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"