version: '3.8'

services:
  app:
    container_name: cv-builder
    build: .
    environment:
      - GIN_MODE=debug
      - ALLOWED_ORIGINS=http://localhost
      - GOTENBERG_URL=http://gotenberg:3000
    ports:
      - "80:80"
    depends_on:
      - gotenberg

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"